"""empty message

Revision ID: 0017a7f05130
Revises: a8fd8ebe8a71
Create Date: 2022-06-28 16:21:13.946820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0017a7f05130'
down_revision = 'a8fd8ebe8a71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
