"""empty message

Revision ID: 23102aefc9f4
Revises: c62e9e363a17
Create Date: 2022-07-15 09:59:21.772934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23102aefc9f4'
down_revision = 'c62e9e363a17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_user_id', table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='conversation_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversation_pkey')
    )
    op.create_index('ix_conversation_user_id', 'conversation', ['user_id'], unique=False)
    # ### end Alembic commands ###
