"""empty message

Revision ID: 2b7aa0053cd9
Revises: eeaf8fe1de5b
Create Date: 2022-06-28 16:31:06.587911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7aa0053cd9'
down_revision = 'eeaf8fe1de5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
