"""empty message

Revision ID: 858290cb5d2c
Revises: 81a642a41652
Create Date: 2022-06-11 17:08:14.317817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858290cb5d2c'
down_revision = '81a642a41652'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attachment', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contact', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contact', 'friend_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conversation', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('message', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.alter_column('message', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'cover_img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'cover_img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.alter_column('message', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('message', 'conversation_id')
    op.alter_column('conversation', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contact', 'friend_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contact', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attachment', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attachment', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
