"""empty message

Revision ID: a8fd8ebe8a71
Revises: 2c75a201be59
Create Date: 2022-06-26 16:56:03.561092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fd8ebe8a71'
down_revision = '2c75a201be59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_column('user', 'cover_img_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cover_img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
