"""empty message

Revision ID: bae60e7c0d06
Revises: 714959a2b802
Create Date: 2022-06-30 11:07:23.289235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae60e7c0d06'
down_revision = '714959a2b802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
