"""empty message

Revision ID: d4b9a52214c7
Revises: ab2717e08885
Create Date: 2022-07-08 13:50:53.748082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b9a52214c7'
down_revision = 'ab2717e08885'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('requester_id', sa.String(), nullable=True))
    op.add_column('contact', sa.Column('accepter_id', sa.String(), nullable=True))
    op.drop_index('ix_contact_friend_id', table_name='contact')
    op.drop_index('ix_contact_user_id', table_name='contact')
    op.create_index(op.f('ix_contact_accepter_id'), 'contact', ['accepter_id'], unique=False)
    op.create_index(op.f('ix_contact_requester_id'), 'contact', ['requester_id'], unique=False)
    op.drop_constraint('contact_friend_id_fkey', 'contact', type_='foreignkey')
    op.drop_constraint('contact_user_id_fkey', 'contact', type_='foreignkey')
    op.create_foreign_key(None, 'contact', 'user', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contact', 'user', ['accepter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contact', 'friend_id')
    op.drop_column('contact', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('friend_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.create_foreign_key('contact_user_id_fkey', 'contact', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('contact_friend_id_fkey', 'contact', 'user', ['friend_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contact_requester_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_accepter_id'), table_name='contact')
    op.create_index('ix_contact_user_id', 'contact', ['user_id'], unique=False)
    op.create_index('ix_contact_friend_id', 'contact', ['friend_id'], unique=False)
    op.drop_column('contact', 'accepter_id')
    op.drop_column('contact', 'requester_id')
    # ### end Alembic commands ###
