"""empty message

Revision ID: dac403ef982a
Revises: bae60e7c0d06
Create Date: 2022-07-07 09:34:01.784809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac403ef982a'
down_revision = 'bae60e7c0d06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('contact', sa.Column('invitation_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'invitation_message')
    op.drop_column('contact', 'created_at')
    # ### end Alembic commands ###
