"""empty message

Revision ID: eeaf8fe1de5b
Revises: 0017a7f05130
Create Date: 2022-06-28 16:28:00.092760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaf8fe1de5b'
down_revision = '0017a7f05130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
